### ISSUE TITLE
Unable to compile in Rust 1.1

### ISSUE THREAD

**Issue by Constan7ine** [KevinKelley/nanovg-rs#15]
After running cargo build I get this output:

```
C:\Users\David\Documents\NanoVGDemo\nanovg-rs>cargo build
   Compiling nanovg v0.2.0 (file:///C:/Users/David/Documents/NanoVGDemo/nanovg-rs)
src\lib.rs:116:15: 116:17 error: expected identifier, found keyword `fn`
src\lib.rs:116     pub const fn rgb_f(r: f32, g: f32, b: f32) -> Color {
                             ^~
src\lib.rs:116:18: 116:23 error: expected `:`, found `rgb_f`
src\lib.rs:116     pub const fn rgb_f(r: f32, g: f32, b: f32) -> Color {
                                ^~~~~
Could not compile `nanovg`.
```

This seemed a simple fix so I removed the const keywords and then was told that optin features builtin_traits and slice patters may not be used in the release channel.

I don't know enough about Rust to go about fixing the code to work in 1.1. Any help would be appreciated

**Comment by KevinKelley** [comment]
I keep tinkering with this too, checking whether it'll compile under the beta or stable channels, and it doesn't, because of those two opt-in features.  I think, given that I'm not messing with it every day, that it would make sense for the project to target "stable" release.  But that means figuring out workarounds for those couple features uses, which I haven't done.

Until I (or somebody) does that, the project requires current-nightly release of Rust.

**Comment by Constan7ine** [comment]
I'm still learning Rust, but when I'm more familiar with it I'll have a go at replacing those features, I'd like to be able to use nanovg in stable rust. 

May I ask, do you have any experience with glfw-rs on windows? It seems fraught with challenges. If not I'll see what they say over on their repo.

**Comment by dleslie** [comment]
I hopped in here to file this very bug! Subscribing. :)

**Comment by dleslie** [comment]
https://github.com/KevinKelley/nanovg-rs/pull/19/commits

Got it working.

**Comment by dleslie** [comment]
This can be closed now.

**Comment by KevinKelley** [comment]
thanks for taking the time with this!
