### ISSUE TITLE
Current state of the API

### ISSUE THREAD

**Issue by Lisoph** [KevinKelley/nanovg-rs#56]
I'd like to collect information on how far the API has come along and what is left to be done, so that we know when we can release a new version of the crate to crates.io.

- What things are left open / missing?
- Is the API stable enough to allow every valid NanoVG program to be ported?
- Any known bugs?

cc @KevinKelley, @zxey

**Comment by zxey** [comment]
As far as I know, only translated Scissors with Intersect scissors does not work as shown in `demo-ui` (described in #44).
There are also few usability problems, I would like to address, implement transforming group of paths at once, instead of passing Some(transform) for every one of them.

**Comment by zxey** [comment]
I think we are ready to publish version 0.4.0, what do you think @KevinKelley, @Lisoph?

**Comment by zxey** [comment]
Yes, I will finish #65 today (hopefully) and the we can probably publish new version. I don't know whether we have to bump version because 0.4 hasn't even been published to crates.io, so we could probably keep 0.4 version with latest changes and publish that.

**Comment by Lisoph** [comment]
I think 1.0.0 is more adequate than 0.4.0, what do you guys think?

**Comment by zxey** [comment]
Yeah, why not, hopefully we are feature complete so we do not have to introduce api breakage with minor versions. But with the amount of changes since 0.3, 1.0 is probably more adequate. I will comment here, when I finish #65.

**Comment by Lisoph** [comment]
Even if we have to introduce api breakage, I don't think that's a problem. We can always push a new major version. Semantic versioning and cargo are great in this regard.

I want to avoid this situation a lot of crate authors have, where they think a 1.0.0 version has to be absolutely perfect, so they keep bumping the minor version and never release a 1.0.0. Bugs and issues will always surface, no software is perfect.

**Comment by zxey** [comment]
Ok, then I think we are good to publish.

**Comment by KevinKelley** [comment]
@zxey  --what is the meaning of the new features syntax, ["nanovg-sys/gl3"] etc?  

crates.io won't accept it... getting errors for bad format feature. Are we being too clever, or does that actually do something?

**Comment by KevinKelley** [comment]
...anyway I reverted that bit and was able to publish, so I'd appreciate hearing any issues I may have caused

**Comment by zxey** [comment]
> The move of 'nanovg' submodule down into 'nanovg-sys' left git with a hanging bad link to the old location.

I had this problem too, and yes it was because of moving the submodule to nanovg-sys, but user of this library should not have this problems, because there was not nanovg submodule in the root of repository for the user.

> I'm guessing here... I think the 'feature ["nanovg-sys/gl3"]' was to cause passing of selected feature down to the nanovg-sys submodule
Yes, correct, it is used as specified [here](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section) in cargo documentation, so it is very strange for me that it does not work with crates.io.

The problem is now, that you have default=["gl3"] and it works, but only for gl3, if I were to specify:
```
[dependencies.nanovg]
version = "0.4.1"
default-features = false
features = ["gl2"]
```
There would be two implementations of nvgCreateGl*, so it needs to be the way it was previously, by passing the feature down.
Can you try to do clean git clone --recursive and publish it again?

**Comment by KevinKelley** [comment]
I did a clean git clone, that's how I found that git was holding a bad link for the upper folder... and Travis failed because each update triggers a clean checkout and build.

If the default being specified, cause the other possibilities to not work... I guess I don't understand what "default" means.  Or somebody doesn't.  Or, anyway, submodules don't...

**Comment by KevinKelley** [comment]
The ghost submodule in git, is/was a separate problem, hopefully solved now...there's stackoverflow discussion if you're curious I can dig the links.

I'm not finding any documentation of what that feature you used, '["nanovg-sys/gl3"] with the slash, is supposed to do.  And with it present, the crates.io 'publish' failed, with an error saying unable to parse.

I've been on the page you linked, the cargo doc, many times, and every day it's got something new, lol, but I still don't see anything about features with slashes, which seems to be what tripped up the crates.io parser.

I think... what you're describing, problem with default feature and specified feature interfering with each other... I'm not sure what to do about that.  My take is that maybe crates.io isn't quite up-to-date on versions, maybe... maybe cargo is still trying to define exactly how overrides should work in all cases...

My comment earlier about us maybe being "too clever" is because of this.  I think it's clever to use all these nice new features, but I don't know if it's really worth the headache, considering how small we are and how fast Rust and cargo are changing.

**Comment by Lisoph** [comment]
I think [this](https://github.com/rust-lang/cargo/issues/633) is the syntax @zxey was trying to use. It was merged into cargo in 2014, so it should work. It does appear to be undocumented though.

> My comment earlier about us maybe being "too clever" is because of this. I think it's clever to use all these nice new features, but I don't know if it's really worth the headache, considering how small we are and how fast Rust and cargo are changing.

I agree, I think us dividing the crate into a sys-subcrate was a bit overkill. A simple ffi.rs source is perfectly adequate for us (other crates do this as well). Should we maybe go back?

---

I didn't have time to try out most of the stuff you guys have been doing over the last few weeks (great work, by the way!), as I have been very busy. I'd like to review all the things that changed since the last time I was active, before we publish -- maybe I can figure out why crates.io rejects the syntax. It should get around it this week.

**Comment by KevinKelley** [comment]
As to "before we publish", that ship has sailed, lol.  In the process of pushing commits so that Travis would run, and cycling back to 'cargo package' and 'publish' for the -sys subcrate and all, I ended up with a 0.4.0 version on crates.io that was broken; so I superceded with a 0.4.1 that is mostly working; the remaining issue is like @zxey says
> The problem is now, that you have default=["gl3"] and it works, but only for gl3

Anyway no big deal.  I've been wanting to spend some time with all our recent changes, think about usability issues and ways to make it more convenient... we have some good work here, and I'm hoping to roll to a version 1.0 soon, and maybe use the version steps below that to work out remaining minor issues.  
So tomorrow I'll think a bit more about whether/not to roll back the -sys subcrate... no problem with it in principle, as long as everything "just works" for us, the maintainers, as well as the users.  

I still hope to be able to have a default mode, so that a random interested bystander can do a clone and build and run, to see the pretty toys and be impressed, without making them have to jump through non-standard hoops for it to work...

**Comment by zxey** [comment]
>  I still don't see anything about features with slashes

It is easily missed, but you can find it in the link I posted:

>  \# Features can be used to reexport features of other packages. The `session`
>  \# feature of package `awesome` will ensure that the `session` feature of the
>  \# package `cookie` is also enabled.
session = ["cookie/session"]

Check example Cargo.toml [here](https://github.com/alexcrichton/git2-rs/blob/master/Cargo.toml), there are reexported features of libgit2-sys and this crate is published to crates.io.

Maybe the problem is that features are declared and are used before nanovg-sys dependency is resolved, try putting `[features]` tag after `[dependencies]` where `nanovg-sys` is defined.

Is there an option for cargo to be more verbose so it can say where exactly it failed parsing? Does `cargo publish -v` work? That should have more verbose output.

If we cannot get this to work, then I will eventually revert nanovg-sys crate, because it would not be worth the headache as you say. But it would be a shame, because I think it is very nicely organized and conform to set conventions.

**Comment by Lisoph** [comment]
I ran into this publish-default-feature issue as well. I think it's a limitation with cargo publish. I asked on reddit about this, and noone could come up with a solution either.

**Comment by Zauberklavier** [comment]
I read around and apparently there is no way to specify exclusive features in cargo. That said there is a more serious problem; namely, specifying the dependency like so:
```toml
nanovg = { version = "0.4.2", features = ["gl2"], default-features = false }
```
causes a linking error. It's very long so I won't paste it here but it ends with:
```
  = note: Undefined symbols for architecture x86_64:
            "_nvgDeleteGL2", referenced from:
                _$LT$nanovg..Context$u20$as$u20$core..ops..drop..Drop$GT$::drop::h0853f0e5b3adc587 in libnanovg-96c2076a8ed134a0.rlib(nanovg-96c2076a8ed134a0.nanovg0.rcgu.o)
            "_nvgCreateGL2", referenced from:
                nanovg::create_gl::hb7a7e6dd7f25723a in libnanovg-96c2076a8ed134a0.rlib(nanovg-96c2076a8ed134a0.nanovg0.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'm guessing this is because nanovg that comes with the bindings is compiled without gl2 support. Is this a bug or am I doing something wrong?

**Comment by KevinKelley** [comment]
Don't know... I've been wondering and not knowing, how the multiple-options thing interacts with native libs... I mean, at the top level you say which feature you want, but does it correctly flow all the way down to the native source?  Sounds like maybe not.

Can't say I've been able to follow every development in how cargo works, so I really can't answer this.  Probably I've done something wrong or at least not taken proper advantage of a feature.

**Comment by Zauberklavier** [comment]
I think may have figured it out. Basically nanovg-dev features have to be conditionally specified based on the feature selected for nanovg-rs.

So if I'm not wrong that would mean instead of:
```toml
[dependencies]
nanovg-sys = { path = "nanovg-sys", version = "0.1.2" }
```
this:
```toml
[target.'cfg(feature = "gl2")'.dependencies]
nanovg-sys = { path = "nanovg-sys", version = "0.1.2", features = ["gl2"], default-features = false }

[target.'cfg(feature = "gl3")'.dependencies]
nanovg-sys = { path = "nanovg-sys", version = "0.1.2", features = ["gl3"], default-features = false }

[target.'cfg(feature = "gles2")'.dependencies]
nanovg-sys = { path = "nanovg-sys", version = "0.1.2", features = ["gles2"], default-features = false }

[target.'cfg(feature = "gles3")'.dependencies]
nanovg-sys = { path = "nanovg-sys", version = "0.1.2", features = ["gles3"], default-features = false }
```
I haven't tested it though and I'm also new to Rust. If you'd like I can submit a patch later. I based this on: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies

Nb. it's weird that the author of nanovg coded the backend implementations in a header file o.O

**Comment by Zauberklavier** [comment]
That turned out to be completely wrong haha. Would you mind if I played around with this to see if I can publish without the default feature and avoid the linking error? The current git version works just fine with the linker but it won't publish, correct?

(apologies to the creator of the ticket, I should really make my own instead of polluting here)

**Comment by KevinKelley** [comment]
I can't take the time at the moment to even figure out for sure what's going wrong.  What you said seemed to make sense...
The underlying nanovg lib is an all-header package, for convenience... so building a lib for us to call from rust is basically a tiny source with the proper defines (to select from the 4 gl opts) and includes.
So... it's a question of passing the proper define (gl2, gl3, whatever) down to the native build... and making it all work with sub-packages and whatnot.  
So yah, fiddly bits that can break when the cargo system changes... anyway yes, I'd be very happy if you wanted to work on it.

**Comment by Lisoph** [comment]
What problems are we currently facing?

**Comment by Zauberklavier** [comment]
We aren't technically. I thought Kevin would merge my branch some time ago but it seems he's busy or otherwise inactive. In the meantime if you want to use backends other than gl3 you can simply use my branch. One caveat right now is that there's no default backend on it so you have to specify one. I think I'll take the time to fix that (it's a _very_ small fix).

**Comment by Lisoph** [comment]
Ok so why did we specify default-features again? I think it's a pretty bad idea to guess the opengl capabilities of the machine. Specifying a feature being mandatory is documented, so to me there is no reason for setting a default. We can publish with `cargo publish --no-verify`, we just need to manually run `cargo build` to see if the crates compile, like the build command would.

**Comment by Zauberklavier** [comment]
If you mean the IFF crate then it's so that `cargo publish` works. If `--no-verify` fixes this too then we can dispense with the defaults like you said (I'm not too familiar with cargo). If you mean the main nanovg crate then it's Kevin's preference. He explained his reasoning in my merge request.

**Comment by Zauberklavier** [comment]
For the record, on my branch, the defaults are specified on the IFF create but then disabled on the main crate so unless you're dealing with the IFF directly there are no defaults.

**Comment by Lisoph** [comment]
I pushed a commit (9301fbf99af7dade6322b68ace6ed57e19e70b87) which readies the crate(s) for publish. I put my rationale behind the changes in the commit message. Feel free to comment.

**Comment by Zauberklavier** [comment]
Looks good 👍

**Comment by KevinKelley** [comment]
Looks good to me; will merge and publish

**Comment by KevinKelley** [comment]
Okay, will re-publish at 1.0.1

**Comment by Zauberklavier** [comment]
Something went wrong with publishing. The directory at `nanovg-sys/nanovg` wasn't published.

Here's a build log from docs.rs: https://docs.rs/crate/nanovg/1.0.1/builds/114049. Same thing happens locally.

**Comment by KevinKelley** [comment]
I see that it's missing; I don't know why... looking at the local folder from which I published, it's there; and demos build and run fine as expected.  So... something wrong in the publish process?  All I did, to publish, was run the `cargo publish --noverify` in the nanovg-sys folder, then in the nanovg-rs parent.

So... to figure out, why was that nanovg subfolder skipped?

**Comment by Zauberklavier** [comment]
That directory is a git repo so maybe you're using some caching mechanism that creates hard links instead of directories and cargo doesn't like that? I'm just guessing.

**Comment by Zauberklavier** [comment]
I can confirm it must be something on your side (or a cargo bug). I ran `cargo package --no-verify` and it included everything. I'm on OS X if that turns out relevant. You can try running `cargo package --no-verify --verbose` as a test.

So, I don't think I can help with this one but we should probably `cargo yank` 1.0.0 and 1.0.1.

**Comment by Lisoph** [comment]
`cargo package --no-verify -v` inside nanovg-sys archives the nanovg submodule, so it's working for me as well I guess. Tested on Windows 10. What's your output, Kevin?

**Comment by KevinKelley** [comment]
...okay, looks like my fault.  I re-cloned the repo, and apparently forgot the "--recursive"; the nanovg subfolder didn't get included.  Too many copies laying around; I guess I published from a different place than I tested.

Anyway, I've `cargo yank` 'ed 1.0.0 and 1.0.1, and published 1.0.2.  Please, check it out and let me know if problems...

**Comment by Lisoph** [comment]
Looks good! The documentation is working fine on docs.rs (nanovg & nanovg-sys).

Well done everyone!

**Comment by Zauberklavier** [comment]
Looks like it works 👍

Shouldn't you also `yank` the parent crate? The way that `yank` works is that those crates that already depend on the broken crate get to keep it so...

**Comment by Lisoph** [comment]
Looks good. I think this issue can be closed.
