### ISSUE TITLE
Borrowing error due to closure bounds on Context::frame(...)

### ISSUE THREAD

**Issue by ennis** [KevinKelley/nanovg-rs#70]
I ran into a somewhat complex borrow checker issue with this snippet:

https://gist.github.com/ennis/eadedc8120b731aa869dc4a5ab53f36d

At line 79, the compiler emits this error:

```
error: borrowed data cannot be stored outside of its closure
  --> src\main.rs:78:46
   |
42 |     let cache = ImageCache::new(&context);
   |         ----- ...so that variable is valid at time of its declaration
...
46 |         context.frame(unimplemented!(), unimplemented!(), |frame| {
   |                                                           ------- borrowed data cannot outlive this closure
...
78 |             let mut renderer = Renderer::new(frame, &cache);
   |                                ------------- ^^^^^ cannot be stored outside of its closure
   |                                |
   |                                cannot infer an appropriate lifetime...

```

With help from the folks over at #rust , I tried to provide an explanation (I put it in the gist). 
In short, it seems that bounds on the callback passed to Context::frame() are too restrictive in some cases. 

https://github.com/KevinKelley/nanovg-rs/blob/e42928f68ffc155a6b1d8d37f2d21189b109a2be/src/lib.rs#L110-L115

Changing the function signature to 
```rust
pub fn frame<'ctx, F: FnOnce(Frame<'ctx>)>(
        &'ctx self,
        (width, height): (i32, i32),
        device_pixel_ratio: f32,
        handler: F,
)
```
seems to fix the issue for me.

**Comment by KevinKelley** [comment]
...it's always painful (for me anyway) when the borrow-checker starts complaining.  Life is better when you can get away with letting it infer lifetimes...

If I'm understanding correctly, (which would be surprising)... it's making a valid complaint.  Drawing to a frame of course depends on the lifetime of the context in which the frame is created... with GL there might to be video-memory to track as well, rendering an image requires its bits to be copied onto the video card, and to stay there until no longer needed...we don't really control it in that much detail, but at some level it has to be managed.

The closure being passed to `frame`, here, is an anonymous fn that lives only as long as the call, so anything created inside it will not outlive it (unless stashed somewhere static).  Your example line 79, `let mut renderer = ...` will expire at the closing brace.  So that should be fine... maybe it's just that, when you put it in a RefCell, now you have to handle `Drop` for it, to avoid there being a leak?  ...you say the compiler stops complaining if you take away RefCell, is that what's going on?

I think I need to run this through the compiler myself and try to better understand...  comments appreciated.  As far as I understand, your fix here (`Frame<`ctx> ... &'ctx self` ) seems fine...

**Comment by Lisoph** [comment]
I think this problem is valid. The issue stems from how Rust elides the lifetimes on `fn frame`. Rust assumes incorrect lifetime rules for `self` and `Frame`. That's a general problem, but it worked for types that are variant over their lifetime(s) because it allowed Rust to subtype these lifetimes. Since no lifetime subtyping is allowed for invariant types (a RefCell-member makes a type invariant), Rust can't choose a "better fitting" lifetime to make it compile. In other words, it works for variant types by accident.

@ennis's fix works by fixing the incorrect elided lifetimes by manually defining them.
At least that's how I understand it with my limited knowledge. I could be totally wrong.

Further reading: [Subtyping and Variance](https://doc.rust-lang.org/nomicon/subtyping.html), [Lifetime Elision](https://doc.rust-lang.org/nomicon/lifetime-elision.html).

**Comment by KevinKelley** [comment]
Sounds good
